[serve.static]
plugins = ["bun-plugin-tailwind"]
env = "BUN_PUBLIC_*"

[test]
preload = ["./test-utils/happydom.ts", "./test-utils/testing-library.ts"]
root = "./src"
coverageReporter  = ["lcov", "text"]
coverageThreshold = 0.1
